version: '3'

services:
  pismo:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysqlsrv
    networks:
      - pismo

  mysqlsrv:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: "p1sm0"
      MYSQL_DATABASE: "pismo"
    ports:
      - "3306:3306"
    networks:
      - pismo

  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - pismo

networks:
  pismo:
    driver: bridge